### ISSUE TITLE
(3) Criar Diagrama MER

### ISSUE THREAD

**Issue by fkfouri** [pbl2018ita/pbl2018#133]
Criar Diagrama MER do planejamento.

**Comment by andersonalvesgomes** [comment]
![mer sprint 2 ts03 - stagiho-bd](https://user-images.githubusercontent.com/7508407/40030480-2bd8dfd2-57c1-11e8-9e45-6b45db0c1d6c.png)
https://drive.google.com/drive/folders/11lhvW1Oh4c2-t_3uUsTUtlLvC2zeLYjk
