### ISSUE TITLE
(2) Modelagem do banco de dados (Tabela, view e Procedure)

### ISSUE THREAD

**Issue by guimanfrim** [pbl2018ita/pbl2018#196]

**Comment by wcristoni** [comment]
Hoje foi criada e publicada a procedure "sp_LocalizarPaciente", que faz a verificação no banco de dados se o paciente já está cadastrado na base local. 
A procedure está utilizando técnicas de query dinâmica, para minimizar o esforço de codificação.

Exemplo de chamada da procedure: call sp_LocalizarPaciente("RG", "11.111.111-1");

O código fonte da procedure pode ser visto em https://github.com/pbl2018ita/pbl2018/blob/master/Time_01/servicos/paciente/script_mysql/SP_LocalizarPaciente.txt
