### ISSUE TITLE
(3) Criar mock (/eventohospital) informações Hospitais (Heroku) salvando o Json no barramento (Kinesis)

### ISSUE THREAD

**Issue by luizcoura** [pbl2018ita/pbl2018#27]

**Comment by andersonalvesgomes** [comment]
Verificar formato da mensagem JSON enviada pelo time1 e time2. Criar as alterações necessárias no objeto JSON

**Comment by luizcoura** [comment]
Abra o browser em https://stagihobd-ts03.herokuapp.com/cross e em seguida abra um terminal e digite:

curl -X POST -H "Content-Type: application/json" -d '{"topic":"teste","message":{"vitima":"X","gravidade":"emergencia","lesao":"fratura","areacorporal":"cabeca","location":{"lat":37.4224764,"lng":-122.0842499}}}' http://192.168.99.100:3000/cross
