### ISSUE TITLE
(1) Criar as entidades e popular mongo

### ISSUE THREAD

**Issue by luizcoura** [pbl2018ita/pbl2018#29]
Capturar uma requisição (request: mensagem JSON) do REGULADOR e auxiliá-lo (response: mensagem JSON) no atendimento da vítima quanto aos procedimentos que serão necessários realizar. Consultar o serviço (endpoint) da US103 para construir esta resposta JSON.

**Comment by fkfouri** [comment]
Criacao de uma transformacao do Pentaho
![image](https://user-images.githubusercontent.com/1031017/38591227-1faf0a12-3d0c-11e8-9189-095a0c025d8c.png)

**Comment by fkfouri** [comment]
Evidencia da carga
![image](https://user-images.githubusercontent.com/1031017/38591282-56449970-3d0c-11e8-87cb-f9ce1db96307.png)
