### ISSUE TITLE
(1) Definir padrão JSON para integração com a US106

### ISSUE THREAD

**Issue by wcristoni** [pbl2018ita/pbl2018#40]
Definir padrão JSON para realizar a integração com o serviço da US106 - para trazer a lista de especialistas do hospital.

**Comment by thalestvba** [comment]
Boa tarde, visto o padrão que foi definido para a US107, acredito que o nosso possa ser semelhante:

{"from": "hc",
"to": "cross",
"content": {
"hospital": {
"identificador": "123456",
"nome": "hc",
"especialistas": {
"especialista1": [
{"crm": "12345","especialidade": "cirurgião"}
]
}
}
}
}

**Comment by wcristoni** [comment]
Integração Finalizada
