### ISSUE TITLE
(3) Fazer curso ou buscar tutoriais de como usar o BigChainDB

### ISSUE THREAD

**Issue by paulodiego01** [pbl2018ita/pbl2018#43]

**Comment by paulodiego01** [comment]
Essa é uma atividade geral, que a pesar de está usando o lable da US111, ela permeia as USs 111, 112 e 113.

**Comment by lineulimasjc** [comment]
Para esta sprint o DB NoSQL MongoDB foi usado. Somente li alguns tutoriais sobre o BigChainDB.
