### ISSUE TITLE
(5) Criação de serviço REST (mockado) 

### ISSUE THREAD

**Issue by guimanfrim** [pbl2018ita/pbl2018#78]

**Comment by jeancarlosfatec** [comment]
Links Externos
Vídeo explicando a configuração do NodeJS no Heroku
https://www.youtube.com/watch?v=AZNFox2CvBk

Tutorial de Testes Unitários, utilizando Mocha
http://www.devfuria.com.br/node.js/testando-javascript-com-o-mocha/
