### ISSUE TITLE
(1) criar o match de especialidade

### ISSUE THREAD

**Issue by andersonalvesgomes** [pbl2018ita/pbl2018#86]

**Comment by luizcoura** [comment]
Abra o browser em https://stagihobd-ts03.herokuapp.com/cross e em seguida abra um terminal e digite:

curl -X POST -H "Content-Type: application/json" -d '{"topic":"teste","message":{"vitima":"X","gravidade":"emergencia","lesao":"fratura","areacorporal":"cabeca","location":{"lat":37.4224764,"lng":-122.0842499}}}' https://stagihobd-ts03.herokuapp.com/cross
