### ISSUE TITLE
(3) Integração com time 2

### ISSUE THREAD

**Issue by guimanfrim** [pbl2018ita/pbl2018#93]

**Comment by wcristoni** [comment]
Foi combinado com o TS#02, as integrações entre VAGA e a interface que eles estão construindo.

Identificamos a necessidade de ajustes no serviço de LEITO (pois hoje ele só mostra os leitos disponíveis e precisamos dos leitos reservados e ocupados), RESERVA e identificamos a necessidade de um novo serviço para fazer a confirmação da reserva (para mudar o status do leito para ocupado), dessa forma combinamos as seguintes tarefas, que serão executadas pelo TS#02:

1. Ajustar o microserviço de RESERVA para uri /leito/reserva
2. Ajustar o JSON, do microserviço de RESERVA, para permitir id_plantonista, id_especialista
3. Ajustar o microserviço de LEITO para permitir o filtro do status ocupado
4. Criar um microserviço /leito/reserva/confirmar?id_paciente=ID
5. Ajustar os 3 ms (LEITO, RESERVA, CONFIRMAR), para gravar no kafka

**Comment by wcristoni** [comment]
Samara, já implementou, conforme mensagem enviada no Slack:

1. Ajustar o microserviço de RESERVA para uri /leito/reserva
2. Ajustar o JSON, do microserviço de RESERVA, para permitir id_plantonista, id_especialista
3. Ajustar o microserviço de LEITO para permitir o filtro do status ocupado
5. Ajustar os 3 ms (LEITO, RESERVA, CONFIRMAR), para gravar no kafka

**Comment by wcristoni** [comment]
Issue Finalizado
